_target_: lightning.Trainer

default_root_dir: ${paths.log_dir}
log_every_n_steps: 1
min_epochs: 1 # prevents early stopping
max_epochs: 3

accelerator: cuda
devices: auto

# reload_dataloaders_every_n_epochs: 5

# limit_train_batches: .2
# limit_test_batches:  .2
# limit_val_batches: .1

# mixed precision for extra speed-up
precision: 16-mixed
# precision: 32  # higher machine

# perform a validation loop every N training epochs
# check_val_every_n_epoch: 1

# set True to to ensure deterministic results
# makes training slower but gives more reproducibility than just setting seeds
deterministic: True

profiler: null #advanced