FROM python:3.12

WORKDIR /opt/src

COPY requirements.txt .

RUN pip install -r requirements.txt && rm -rf /root/.cache/pip

RUN gdown 1HHSFrklRPpoHGlggmBkUSjSg4tCrNANY --output /opt/src/mambaout_model_vegfruit.onnx

RUN gdown 1HHSFrklRPpoHGlggmBkUSjSg4tCrNANY --output /opt/src/mambaout_model_sports.onnx

COPY server.py .

CMD ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8080"]