name: Deployment 01C - PR Trigger Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - dev_1

# on:
#   workflow_dispatch:

jobs:

  trigger-train:
    uses: ./.github/workflows/01D_Deployment_PR_Train_And_Store.yaml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ECR_LOGIN_URI: ${{ secrets.AWS_ECR_LOGIN_URI }}
      ECR_REPOSITORY_NAME: ${{ secrets.ECR_REPOSITORY_NAME }}
      AWS_SECURITY_GROUP_ID: ${{ secrets.AWS_SECURITY_GROUP_ID }}
      AWS_SUBNET_ID_1: ${{ secrets.AWS_SUBNET_ID_1 }}
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

